---
#
# The file <ansible_topdir>/group_vars/all contains:
#
#    ---
#    provider:
#      mmurl: http://micetro.example.net
#      user: apiuser
#      password: apipasswd
#
- name: Men&Mice zone test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ansible information
      debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Ensure the zone
      mm_zone:
        state: present
        name: example.com
        nameserver: micetro.example.com
        authority: micetro.example.net
        masters: micetro.example.net
        servtype: master
        customproperties:
          owner: Me, myself and I
          place: Netherlands
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Remove the zone
      mm_zone:
        state: absent
        name: example.com
        provider: "{{ provider }}"
      delegate_to: localhost
