---
#
# Make a DHCP reservation and release it on the Men&Mice Suite example
#
# The file <ansible_topdir>/group_vars/localhost contains:
#
#    ---
#    provider:
#      mmurl: http://mmsuite.example.net
#      user: apiuser
#      password: apipasswd
#
- name: Men&Mice DHCP test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ansible information
      debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Add a reservation for an IP address
      mm_dhcp:
        state: present
        name: myreservation
        ipaddress: 172.16.17.8
        macaddress: 44:55:66:77:88:00
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: check idempotentie
      mm_dhcp:
        state: present
        name: myreservation
        ipaddress: 172.16.17.8
        macaddress: 44:55:66:77:88:00
        provider: "{{ provider }}"
      delegate_to: localhost

    # Changing the MAC address of a reservation is not allowed, as this
    # would alter the reservation. To achieve this, release the reservation
    # and reclaim it.
    - name: change mac
      mm_dhcp:
        state: present
        name: myreservation
        ipaddress: 172.16.17.8
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: change ip
      mm_dhcp:
        state: present
        name: myreservation
        ipaddress: 172.16.17.9
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: change name
      mm_dhcp:
        state: present
        name: movemyreservation
        ipaddress: 172.16.17.9
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: delete reservation (wrong one)
      mm_dhcp:
        state: absent
        name: movemyreservation
        ipaddress: 172.16.17.9
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: delete reservation (correct one)
      mm_dhcp:
        state: absent
        name: myreservation
        ipaddress: 172.16.17.8
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: create reservation in invalid range
      mm_dhcp:
        state: present
        name: reservationnonet
        ipaddress: 172.16.17.58
        macaddress: 44:55:66:77:88:99
        provider: "{{ provider }}"
      delegate_to: localhost
