---
#
# Get all info for an IP address in Micetro example
#
# The file <ansible_topdir>/group_vars/all contains:
#
#    ---
#    provider:
#      mmurl: http://micetro.example.net
#      user: apiuser
#      password: apipasswd
#
- name: Men&Mice IP Info test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Get get IP info
      set_fact:
        ipinfo: "{{ query('mm_ipinfo', provider, '172.16.17.2') | to_nice_json }}"

    - name: Show Ansible and Python information
      debug:
        msg:
          - "Ansible version    : {{ ansible_version.full }}"
          - "Python version     : {{ ansible_facts['python_version'] }}"
          - "Python executable  : {{ ansible_facts['python']['executable'] }}"

    - name: Show all infor for this IP address
      debug:
        var: ipinfo

    # This task tries to get the information for a non-existing IP address
    # which results in a fatal `Object not found for reference` error
    - name: Get get IP info for a non existing IP address
      set_fact:
        ipinfo: "{{ query('mm_ipinfo', provider, '390.916.17.2') | to_nice_json }}"
      ignore_errors: true
