---
- name: Men&Mice DNSRecord test play
  hosts: localhost
  connection: local
  become: false

  vars:
    provider:
      mmurl: http://mandm.example.net
      user: apidude
      password: TheAPIDude

  tasks:
    - name: Ansible information
      debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Set DNS record
      mm_dnsrecord:
        state: present
        name: beatles
        rrtype: A
        dnszone: testzone
        data: 192.168.10.12
        comment: From The API side
        ttl: 86400
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Check idempotentie
      mm_dnsrecord:
        state: present
        name: beatles
        rrtype: A
        dnszone: testzone
        data: 192.168.10.12
        comment: From The API side
        ttl: 86400
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Change record
      mm_dnsrecord:
        state: present
        name: beatles
        rrtype: A
        dnszone: testzone
        data: 192.168.10.14
        comment: From The API side
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Do something stupid
      mm_dnsrecord:
        state: present
        name: beatles
        rrtype: A
        dnszone: notthetestzone
        data: 192.168.90.14
        comment: Welcome to the error
        provider: "{{ provider }}"
      delegate_to: localhost
      ignore_errors: true

    - name: Do more something stupid things
      mm_dnsrecord:
        state: present
        name: beatles
        rrtype: A
        dnszone: testzone
        data: 192.168.390.14
        comment: Welcome to the error
        provider: "{{ provider }}"
      delegate_to: localhost
      ignore_errors: true

    - name: Remove record
      mm_dnsrecord:
        state: absent
        name: beatles
        dnszone: notthetestzone
        data: 192.168.90.14
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Remove record - again
      mm_dnsrecord:
        state: absent
        name: beatles
        dnszone: notthetestzone
        data: 192.168.90.14
        provider: "{{ provider }}"
      delegate_to: localhost
