---
- name: Men&Mice IP Info test play
  hosts: localhost
  connection: local
  become: false

  vars:
    provider:
      mmurl: http://mandm.example.net
      user: apidude
      password: TheAPIDude

  tasks:
    - name: Set get IP info
      set_fact:
        ipinfo: "{{ query('mm_ipinfo', provider, '172.16.17.2') }}"

    - name: Get the free IP address and show info
      debug:
        msg:
          - "IP Info            : {{ ipinfo }}"
          - "Ansible version    : {{ ansible_version.full }}"
          - "Python version     : {{ ansible_facts['python_version'] }}"
          - "Python executable  : {{ ansible_facts['python']['executable'] }}"
