#!/bin/bash
# vi: set sw=4 ts=4 ai:
CRD="$( [[ "${0:0:2}" = "./" ]] &&
	{	printf "${PWD}/${0#./}"
	} || {
		printf "${0}"
	})"
CRD="${CRD%/*}"


fmt() {
	printf -- "${*}" | awk '
			BEGIN {
				MRG=""
				ML=74 - length(MRG)
			}
			{	NRWORDS = split($0, WORDS)
				LENGTH = 0
				printf("%s", MRG)

				for (CNT = 1; CNT <= NRWORDS; CNT++) {
					LENGTH = LENGTH + length(WORDS[CNT])
					if (LENGTH >= ML) {
						printf ("\n  %s%s ", MRG, WORDS[CNT])
						LENGTH = length(WORDS[CNT]) + 1
					} else {
						printf ("%s ", WORDS[CNT])
						LENGTH = LENGTH + 1
					}
				}
			}
			END {
				printf ("\n")
			}' | sed 's/[ 	][ 	]*$//'
}

PLUGINS='
	mm_claimip
	mm_dhcp
	mm_dnsrecord
	mm_ipprops
	mm_props
	mm_user
	mm_zone
'

# As Ansible doc automatically wraps lines for the the
# screen width, the width needs to be faked (8192 max)
COLS="$(stty -a | awk -F';' '/columns/ { print $3 }')"
export COLUMNS=4096
stty columns ${COLUMNS}

export PYTHONPATH=${CRD}/../library:${PYTHONPATH}

cat <<- @EOF
# Ansible modules

Effectively and efficiently manage DNS, DHCP, IPAM and Users with the Men&Mice
Suite through a set of Ansible modules, inventory and lookup plugins.

All available modules are documented below. The plugins each have their
own documentation.

- [\`freeip\`](README_freeip.md)
- [\`inventory\`](README_inventory.md)
- [\`ipinfo\`](README_ipinfo.md)
@EOF

# Now process all modules
for p in $(echo "${PLUGINS}" | sort)
do
	echo
	echo "## ${p}"
	echo
	ansible-doc -s ${p}									| \
		sed -n '/^- name:/ {s/- name: //; p}'			| \
			while read line
			do
				fmt "${line}"
			done

	echo
	echo "### Options"
	echo

	ansible-doc -s ${p}									| \
		sed -n '/^    */ { s/^   */- /; p}'				| \
		sed	-e '/^- state/ s/$/ (`absent`, `present`)/'	\
			-e 's/:  *# /: /'							\
			-e "s/'/\`/g"								\
			-e 's/^- \([^ ]*\):/- `\1`:/'				| \
			while read line
			do
				fmt "${line}"
			done
	echo
	echo "### Examples"
	echo
	echo '```yaml'
	echo "import ${p}; print(${p}.EXAMPLES)" | python3 | sed '1d;$d'
	echo '```'
done
stty ${COLS}
