#!/bin/bash

PLUGINS='
	mm_claimip
	mm_dhcp
	mm_dnsrecord
	mm_ipprops
	mm_props
	mm_zone
'

for p in ${PLUGINS}
do
	echo
	echo "### ${p}"
	echo
	ansible-doc -s ${p}						| \
		sed -n '/^- name:/ {s/- name: //; p}'

	echo
	echo "#### Options"
	echo

	ansible-doc -s ${p}						| \
		sed -n '/^    */ { s/^   */- /; p}'			| \
		sed	-e '/^- state/ s/$/ (absent, present)/'		\
			-e 's/:  *# /: /'				\
			-e "s/'/\`/g"					\
			-e 's/^- \([^ ]*\):/- `\1`:/'

done
