== Ansible setup for Men&Mice Suite

With the Ansible setup for the Men&Mice suite you can manage a Men&Mice
installation through Ansible. The Ansible modules and plugins connect to
the Men&Mice Suite API and perform all needed actions.

The modules and plugins need to be installed on the Ansible control
node, often called the Ansible Master and Ansible needs to be configured
so that the modules and plugins can be found by Ansible.

=== Installation

Installing the Ansible modules and plugins is a straight forward
process. Copy the Ansible modules and plugins to a directory on the
Ansible control node, let us assume `/tmp/mandm`.

==== Ansible modules

The Ansible modules can than be placed in a number of directories,
depending on your installation and requirements.

[arabic]
. `/usr/share/ansible/plugins/modules/` System wide installation,
modules available to all users
. `~/.ansible/plugins/modules/` Modules available only to the current
user, as the modules are installed in the users home-directory
. `/etc/ansible/library/` Local installation. As most Ansible
installations use the `/etc/ansible` directory as the Ansible
top-directory (as this is the default in an Ansible installation), this
is probably the best installation option. When installing the modules in
this directory, the Ansible `library` path needs to be set in the
`/etc/ansible/ansible.cfg` file, pointing to the module directory.

[source,bash]
----
library = /etc/ansible/library
----

After installing the Ansible modules a check can be run to determine if
the modules are installed correctly, by running the command:

[source,bash]
----
ansible-doc -l | grep '^mm_'
----

This should produce a list with all the Men&Mice Suite Ansible modules.

==== Ansible lookup plugins

The set of Ansible modules consists of multiple sets (`lookup` and
`inventory`) and these should be installed in their own directories

The `lookup` plugins can be installed in:

[arabic]
. `/usr/share/ansible/plugins/lookup` System wide installation, modules
available to all users
. `~/.ansible/plugins/lookup` Plugins available only to the current
user, as the plugins are installed in the users home-directory
. `/etc/ansible/plugins/lookup` Local installation. As most Ansible
installations use the `/etc/ansible` directory as the Ansible
top-directory (as this is the default in an Ansible installation)this is
probably the best installation option. When installing the lookup
plugins in this directory, the Ansible `lookup` path needs to be set in
the `/etc/ansible/ansible.cfg` file, pointing to the lookup plugin
directory.

[source,bash]
----
lookup_plugins = /usr/share/ansible/plugins/lookup:/etc/ansible/plugins/lookup
----

To check if the modules are installed correctly and are available to
Ansible, issue the command:

[source,bash]
----
ansible-doc -t lookup -l
----

Which should produce a list with all the Men&Mice Suite Ansible lookup
plugins.

==== Ansible inventory plugins

The set of Ansible modules consists of multiple sets (`lookup` and
`inventory`) and these should be installed in their own directories

The `inventory` plugins can be installed in:

[arabic]
. `/usr/share/ansible/plugins/inventory` System wide installation,
modules available to all users
. `~/.ansible/plugins/inventory` Plugins available only to the current
user, as the plugins are installed in the users home-directory
. `/etc/ansible/plugins/inventory` Local installation. As most Ansible
installations use the `/etc/ansible` directory as the Ansible
top-directory (as this is the default in an Ansible installation) this
is probably the best installation option. When installing the inventory
plugins in this directory, the Ansible `lookup` path needs to be set in
the `/etc/ansible/ansible.cfg` file, pointing to the lookup plugin
directory.

[source,bash]
----
inventory_plugins = /usr/share/ansible/plugins/inventory:/etc/ansible/plugins/inventory
----

To check if the modules are installed correctly and are available to
Ansible, issue the command:

[source,bash]
----
ansible-doc -t inventory -l
----

Which should produce a list with all the Men&Mice Suite Ansible
inventory plugins.

The `mm_inventory` plugin also needs some extra configuration, read the
`README_inventory.md` for more information.

=== API user

As the Ansible modules and plugins connect to a Men&Mice Suite
installation, a connection between Ansible and the Men&Mice Suite needs
to be made.

==== API user for Men&Mice Suite

In the Men&Mice Suite a user needs to be defined that has all rights in
the Men&Mice Suite (`administrator`) so it is able to perform all needed
tasks.

==== API Provider in Ansible

For the Ansible modules and plugins to function correctly a _provider_
has to be defined. This provider consist of a `user`, `password` and
connection url (`mmurl`) and this provider needs to be defined in the
Ansible setup, either through Ansible Tower/AWX or in the Ansible
directory.

As the modules and plugins can be used by all systems under Ansible
control, it is advised to define the API provider for the `all` group.
Create a file `all` in the `/etc/ansible/group_vars` directory, or the
`/etc/ansible/inventory/group_vars` directory (if your inventory is a
directory instead of a file) which contains something similar to:

[source,yaml]
----
---
provider:
  mmurl: http://mmsuite.example.net
  user: apiuser
  password: apipasswd
----

Where the `apipasswd` should be encrypted with `ansible-vault` to
prevent plain passwords in the Ansible tree. An example to achieve this
is

[source,bash]
----
printf "apipasswd"             | \
    ansible-vault              \
        encrypt_string         \
        --stdin-name="password"
----

Which results in:

[source,bash]
----
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34646538383265336162666535313938333861323465333661376436656637643434316266666430
  6139656636383537336365313165663861383165616632330a333230356662336161393439666431
  35393130656565313138383565626137353639316239393735306663376362613861623135656634
  6332393063643531390a343661373263656132363737326666396132373461323631613034356565
  6138
----

The defined provider can be used in Ansible playbooks like:

[source,yaml]
----
- name: Claim IP address
  mm_claimip:
    state: present
    ipaddress: 172.16.12.14
    provider: "{{ provider }"
  delegate_to: localhost
----

The reason for the `delegate_to: localhost` option, is that all commands
can be performed on the Ansible control node. So, it is possible to
protect the Men&Mice Suite API to only accept commands from the Ansible
control node and not from everywhere. This can also be achieved by
creating a playbook that has a connection with `localhost` and is
specific for the interaction with the Men&Mice Suite.

[source,yaml]
----
---
- name: host connection example
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Claim IP address
      mm_claimip:
        state: present
        ipaddress: 172.16.12.14
        provider: "{{ provider }"
----

=== Ansible configuration example

Beneath the is an example Ansible configuration file (`ansible.cfg`)
with the assumption that all Men&Mice plugins and modules are installed
in the `/etc/ansible` directory.

[source,bash]
----
# ==============================================
[defaults]
remote_tmp              = $HOME/.ansible/tmp
inventory               = inventory
pattern                 = *
forks                   = 5
poll_interval           = 15
ask_pass                = False
remote_port             = 22
remote_user             = ansible
gathering               = implicit
host_key_checking       = False
interpreter_python      = auto_silent
force_valid_group_names = true
retry_files_enabled     = False
library                 = /etc/ansible/library
action_plugins          = /usr/share/ansible_plugins/action_plugins
callback_plugins        = /etc/ansible/plugins/callback_plugins
connection_plugins      = /usr/share/ansible_plugins/connection_plugins
filter_plugins          = /usr/share/ansible_plugins/filter_plugins
inventory_plugins       = /usr/share/ansible_plugins/inventory_plugins:/etc/ansible/plugins/inventory
lookup_plugins          = /usr/share/ansible_plugins/lookup_plugins:/etc/ansible/plugins/lookup
vars_plugins            = /usr/share/ansible_plugins/vars_plugins
callback_whitelist      = minimal, dense, oneline
stdout_callback         = default

[inventory]
enable_plugins   = mm_inventory, host_list, auto
cache            = no
cache_plugin     = pickle
cache_prefix     = mm_inv
cache_timeout    = 60
cache_connection = /tmp/mm_inventory_cache

[privilege_escalation]
become          = False
become_method   = sudo
become_user     = root
become_ask_pass = False
----
