=== mm_zone

Manage DNS zones in Micetro

==== Options

- `adintegrated`: True if the zone is Active Directory integrated.
- `adpartition`: The AD partition if the zone is Active Directory
  integrated.
- `adreplicationtype`: Type of the AD replication.
- `authority`: Name of the DNS server that contains the zone or the
  string `[Active Directory]` if the zone is integrated in the Active
  Directory.
- `customproperties`: Custom properties for the zone. These properties
  must already exist. See also [mm_props].
- `dynamic`: Dynamic DNS zone.
- `masters`: The IP addresses of the master servers if the new zone is
  not a master zone.
- `name`: (required) Name of the zone.
- `nameserver`: Nameserver to define the zone on. Required if
  `state=present`.
- `provider`: (required) Definition of the Micetro API provider.
- `servtype`: Type of the master server.
- `state`: The state of the zone. (`absent`, `present`)

==== Examples

.Zone example
[source,yaml]
----
- name: Create a new zone
  mm_zone:
    state: present
    name: example.com
    nameserver: ns1.example.com
    authority: micetro.example.net
    customproperties:
      location: Reykjavik
    provider:
      mmurl: http://micetro.example.net
      user: apiuser
      password: apipasswd
  delegate_to: localhost

- name: Release a zone
  mm_zone:
    state: absent
    name: example.com
    provider:
      mmurl: http://micetro.example.net
      user: apiuser
      password: apipasswd
  delegate_to: localhost
----
