#!/bin/bash
# vi: set sw=4 ts=4 ai:
CRD="$( [[ "${0:0:2}" = "./" ]] &&
	{	printf "${PWD}/${0#./}"
	} || {
		printf "${0}"
	})"
CRD="${CRD%/*}"


fmt() {
	printf -- "${*}" | awk '
			BEGIN {
				MRG=""
				ML=74 - length(MRG)
			}
			{	NRWORDS = split($0, WORDS)
				LENGTH = 0
				printf("%s", MRG)

				for (CNT = 1; CNT <= NRWORDS; CNT++) {
					LENGTH = LENGTH + length(WORDS[CNT])
					if (LENGTH >= ML) {
						printf ("\n  %s%s ", MRG, WORDS[CNT])
						LENGTH = length(WORDS[CNT]) + 1
					} else {
						printf ("%s ", WORDS[CNT])
						LENGTH = LENGTH + 1
					}
				}
			}
			END {
				printf ("\n")
			}' | sed 's/[ 	][ 	]*$//'
}

PLUGINS='
	mm_claimip
	mm_dhcp
	mm_dnsrecord
	mm_ipprops
	mm_props
	mm_user
	mm_zone
'

# As Ansible doc automatically wraps lines for the the
# screen width, the width needs to be faked (8192 max)
COLS="$(stty -a | awk -F';' '/columns/ { print $3 }')"
export COLUMNS=4096
stty columns ${COLUMNS}

export PYTHONPATH=${CRD}/library:${PYTHONPATH}

(cat <<- @EOF
=== Ansible modules

@EOF

# Now process all modules
for p in $(echo "${PLUGINS}" | sort)
do
	echo
	echo "=== ${p}"
	echo
	ansible-doc -s ${p}									| \
		sed -n '/^- name:/ {s/- name: //; p}'			| \
			while read line
			do
				fmt "${line}"
			done

	echo
	echo "==== Options"
	echo

	ansible-doc -s ${p}									| \
		sed -n '/^    */ { s/^   */- /; p}'				| \
		sed	-e '/^- state/ s/$/ (`absent`, `present`)/'	\
			-e 's/:  *# /: /'							\
			-e "s/'/\`/g"								\
			-e 's/^- \([^ ]*\):/- `\1`:/'				| \
			while read line
			do
				fmt "${line}"
			done
	echo
	echo "==== Examples"
	echo
	echo "[source,yaml]"
	echo '----'
	echo "import ${p}; print(${p}.EXAMPLES)" | python3 | sed '1d;$d'
	echo '----'
done) > docs/README_modules.adoc

# Add example playbooks

(cat <<- @EOF
	== Example playbooks

	To use the Men&Mice Suite Ansible Integration you need to create
	playbooks that utilize the functionality of the Men&Mice Suite.

	Following are a couple of example playbooks for inspiration.

	These playbooks have been tested on CentOS7, CentOS8 and Ubuntu 18.04  with
	Ansible 2.7, 2.8 and 2.9, all using Python2 and Python3.

	Caveat: As the operating systems do not have all these combinations of
	Ansible and Python available, the tests where done in Python virtual
	environments.

	All these playbooks are available in the \`examples\` directory.
@EOF

for f in docs/examples/*yml
do
	play=$(basename ${f} .yml)
	echo
	echo "=== ${play}"
	echo
	echo "[source,yaml]"
	echo '----'
	cat ${f}
	echo '----'
done) > docs/README_playbooks.adoc
stty ${COLS}
