---
- name: Men&Mice ClaimIP test play
  hosts: localhost
  connection: local
  become: false

  vars:
    provider:
      mmurl: http://mandm.example.net
      user: apidude
      password: TheAPIDude

  tasks:
    - name: Ansible information
      debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Claim IP address
      mm_claimip:
        state: present
        ipaddress: 172.16.12.14
        provider: "{{ provider }"
      delegate_to: localhost

    - name: Check idempotentie
      mm_claimip:
        state: present
        ipaddress: 172.16.12.14
        provider: "{{ provider }"
      delegate_to: localhost

    - name: Unclaim IP address
      mm_claimip:
        state: present
        ipaddress: 172.16.12.14
        provider: "{{ provider }"
      delegate_to: localhost

    - name: Claim stupid IP address
      mm_claimip:
        state: present
        ipaddress: 456.978.12.14
        provider: "{{ provider }"
      delegate_to: localhost

