== Ansible Integration for Micetro by Men&Mice

=== What is Micetro by Men&Mice?

Micetro by Men&Mice is a transformation-ready, automation-enabled,
comprehensive DDI orchestration solution for your enterprise network,
regardless of its location, scale or complexity.

Easily manage DNS and DHCP servers and networking devices such as
firewalls and routers. Get the visibility and management functionality
you need across your entire network, whether on-prem, hybrid or
multi-cloud.

The Men&Mice Web Application enables quick access to the most commonly
used DNS and DHCP management functions and reports of Micetro.

See also: https://menandmice.com

=== Ansible integration

With the Ansible setup for Micetro by Men&Mice you can manage a Micetro
installation through Ansible. The Ansible modules and plugins connect to
the Men&Mice API and perform all needed actions.

The modules and plugins need to be installed on the Ansible control
node, often called the Ansible Master and Ansible needs to be configured
so that the modules and plugins can be found by Ansible.

The file `ansible.cfg_example` contains an example configuration that
you can use with the Ansible modules and plugins for Micetro.

For the complete documentation, see the `docs` directory.

Please enjoy.
	The Men&Mice Team
