== Ansible Integration for the Men&Mice Suite

=== What is the Men&Mice Suite?

Effectively and efficiently manage DNS, DHCP and IPAM with the Men&Mice
Suite.

Easily manage DNS and DHCP servers and networking devices such as
firewalls and routers. Get the visibility and management functionality
you need across your entire network, whether on-prem, hybrid or
multi-cloud.

The Men&Mice Web Application enables quick access to the most commonly
used DNS and DHCP management functions and reports of the Men&Mice
Suite.

See also: https://www.menandmice.com

=== Ansible integration

With the Ansible setup for the Men&Mice suite you can manage a Men&Mice
installation through Ansible. The Ansible modules and plugins connect to
the Men&Mice Suite API and perform all needed actions.

The modules and plugins need to be installed on the Ansible control
node, often called the Ansible Master and Ansible needs to be configured
so that the modules and plugins can be found by Ansible.

The file `ansible.cfg_example` contains an example configuration that
you can use with the Ansible modules and plugins for the Men&Mice Suite.

For the complete documentation, see the `docs` directory.

Please enjoy.
	The Men&Mice Team
