#!/bin/bash
# When run like: DEBUG=1 ./run play_dhcp.yml
# Ansibles debug is turned on, with '-vvvv'

if [[ ${#} -lt 1 ]]
then
	echo "Need a playbook to run" >&2
	exit 1
fi

# Two parameters, first one is Pyton / Ansible version
if [[ ${#} -eq 2 ]]
then
	PYANS="${1}"
	shift
else
	PYANS="p2_ans27 p2_ans28 p2_ans29 p3_ans27 p3_ans28 p3_ans29"
fi

# Check DEBUG
[[ ${DEBUG:-0} -eq 1 ]] && DBG='-vvvv' || DBG=''
export DBG

# And loop di loop
for f in ${PYANS}
do
	echo
	echo "= Running for ${f} ========================================================="
	echo

	# Export everything, because we run all commands in a subshell to prevent
	# tainting the environment
	export f
	export PYTHVER=$(echo ${f%%_*} | tr -d 'p')
	[[ ${PYTHVER} -eq 2 ]] && PYTHVER="2.7" || PYTHVER="3.6"

	(. ../../${f}/bin/activate
	export ANSIBLE_PYTHON_INTERPRETER=${PWD}/../../${f}/bin/python
	ansible-playbook ${DBG} -e 'ansible_python_interpreter="/usr/bin/env python"' "${@}" 0</dev/null
	)
done
