#!/bin/bash
# vi: set sw=4 ts=4 ai:

rm ../library/*
cp -p COPYING ../library
touch ../library/__init__.py
for f in mm_*.py
do
	echo "Converting ${f}"
	cp -p header ../library/${f}
	sed												\
		-e '/^#IMPORTS_END/r imports'				\
		-e '/^#IMPORTS_START$/,/^#IMPORTS_END$/d'	\
		-e '/^#IMPORT_INCLUDE$/r include.py'		\
		-e '/^#IMPORT_INCLUDE$/d'					\
		-e 's/ mm\./ /g'							\
		${f} >> ../library/${f}
	done
